### ISSUE TITLE
Getting raw data

### ISSUE THREAD

**Issue by Muszashi** [ozlerhakan/poiji#138]
Hi Guys, it is more like a change request. 

It would be nice to have an option to be able to get not only the visible data but the underlying raw data as well.

Like I have a numeric field, the visible content is: 0.1118 however the raw, underlying data is 0.111758. The data I got back is 0.1118 however I would need the whole raw data. 

Thank you in advance,

Ps: Very useful library.

**Comment by ozlerhakan** [comment]
Hi @Muszashi ,

Thank you for the suggest first. In which excel file type (xls or xlsx) you need this case?

**Comment by Muszashi** [comment]
Thank you for the quick response. 

In my case it would be xlsx file type

**Comment by ozlerhakan** [comment]
Hi @Muszashi , could I have an example excel file for this case?

**Comment by ozlerhakan** [comment]
feel free to leave a comment, we can open it again

**Comment by fer8419** [comment]
Hi.

I have been having this same problem. For example I have a column with a slightly long number, and instead of getting the original number I get the one that is displayed, for example 5.73147E + 11
instead of 573146569885. I am getting it as string. I am attaching a file with an example cell. 

[sample_error.xlsx](https://github.com/ozlerhakan/poiji/files/6469964/sample_error.xlsx)

Thanks.

**Comment by ozlerhakan** [comment]
Hi @fer8419  and @Muszashi , you can use v3.1.1 to retrieve raw data of cells in excel files.
