### ISSUE TITLE
Support functions like'Stream'?

### ISSUE THREAD

**Issue by glqdlt** [ozlerhakan/poiji#171]
Hello

I have to use the big table.

The record count for tables in the database is over 100K (100,000).

Do you support functions like'Stream'?

Or is there a function to create a file and append to it?

**Comment by ozlerhakan** [comment]
Hi @glqdlt ,

How exactly do you want to use Stream API? The size of the excel does not matter for poiji, did you check https://github.com/ozlerhakan/poiji#feature-6  as well?

**Comment by ozlerhakan** [comment]
feel free to add your comment, until now I'm closing it

**Comment by vaa25** [comment]
@glqdlt maybe [this one](https://mvnrepository.com/artifact/io.github.vaa25/poiji2) can help you

**Comment by ozlerhakan** [comment]
so sad that I see this sentence in your @vaa25  forked poiji: `Great thanks to ozlerhakan that ignored my pull requests.`

even I said this in the PR:

> thank you for your effort @vaa25 , since this is a big change for poiji, I need to look at them closely however, currently I don't have time to do that :/ Let's keep it here for now

I haven't said "I am rejecting your PR or anything that implies something about rejecting" please do your PR again 🙏 or correct your sentence in order to avoid a misunderstanding 🤗
