### ISSUE TITLE
BigDecimals do not use the provided Locale from PoijiOptions

### ISSUE THREAD

**Issue by beckerdennis** [ozlerhakan/poiji#215]
If a column is parsed as `BigDecimal`, the parser will always use the system default `Locale`. That causes my unit tests to fail either in my build pipeline (`Locale.US`) or on my device locally (`Locale.GERMANY`)

**Comment by ozlerhakan** [comment]
Hi @beckerdennis ,

Thank you for contributing Poiji. I see that we don't use Locale for the bigDecimal https://github.com/ozlerhakan/poiji/blob/398d2e10a8b4011f17f3b49df65e656b7e4e8b8e/src/main/java/com/poiji/config/DefaultCasting.java#L135

Do you want to make available this behavior for big decimal numbers via PR? otherwise I will do it.

**Comment by ozlerhakan** [comment]
Ah I see your PR already! thank you @beckerdennis , I will check it on weekend

**Comment by beckerdennis** [comment]
Hi @ozlerhakan 
I just created a PR with the required changes :)

**Comment by ozlerhakan** [comment]
you can use now poiji 3.1.4 @beckerdennis , thanks again :)
